apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - nginx.lin2ur.cn
    resources:
      - reverseproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nginx.lin2ur.cn
    resources:
      - reverseproxies/finalizers
    verbs:
      - update
  - apiGroups:
      - nginx.lin2ur.cn
    resources:
      - reverseproxies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - nginx.lin2ur.cn
    resources:
      - tcpreverseproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nginx.lin2ur.cn
    resources:
      - tcpreverseproxies/finalizers
    verbs:
      - update
  - apiGroups:
      - nginx.lin2ur.cn
    resources:
      - tcpreverseproxies/status
    verbs:
      - get
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
